# Generated by Django 4.2.2 on 2024-03-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('SL_no', models.AutoField(primary_key=True, serialize=False)),
                ('ID', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=50)),
                ('Group', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=20)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
    ]
